// Programa artístico (cartel Kontrast). [fecha, hora, obra, compañía | null, disciplina, lugar]
// Cuando no hay compañía (conciertos, DJs, charlas…) la tarjeta usa el nombre de la obra.
const D = (n) => `2025-04-${String(n).padStart(2, '0')}`;
export const PROGRAMA = [
  [D(10), '18:00', 'Kamchàtka', 'Kamchàtka', 'TEATRE de CARRER', 'Gironella'],
  [D(10), '19:30', 'Copyleft', 'Cie. NDE Nicanor de Elia', 'CIRC', 'Gironella'],
  [D(10), '22:00', 'Décrochez-moi ça', 'Bêtes de Foire', 'CIRC', 'Cal Rosal'],
  [D(10), '23:30', 'Compost Collaps + ERREURJEAN', null, 'MÚSICA', 'Cal Rosal'],
  [D(11), '12:00', 'Miror', 'Muchmuche Company', 'CIRC', 'Casserres'],
  [D(11), '17:00', 'Rose Bif', 'Sarah Anglada', 'TEATRE-DANSA', 'KONVENT'],
  [D(11), '19:00', 'Walk in Progress', 'Claudio Stellato + Pablo Molina', 'CIRC', 'KONVENT'],
  [D(11), '21:30', 'Dolores', 'My!Laika', 'CIRC', 'Cal Rosal'],
  [D(11), '23:30', 'Konvent Klub', null, 'MÚSICA', 'KONVENT'],
  [D(12), '13:30', 'Inutile Randonnée', null, 'MÚSICA', 'KONVENT'],
  [D(12), '14:30', 'Dinar Popular', null, 'DINAR', 'KONVENT'],
  [D(12), '16:00', 'Miror', 'Muchmuche Company', 'CIRC', 'Cal Rosal'],
  [D(12), '17:30', 'Bleu Électrique (WIP)', 'Cirque Pardí!', 'CIRC', 'Cal Rosal'],
  [D(12), '19:00', 'Décrochez-moi ça', 'Bêtes de Foire', 'CIRC', 'Cal Rosal'],
  [D(12), '20:30', 'Cru Lab (Creació Express)', null, 'CIRC i MÚSICA', 'Cal Rosal'],
  [D(16), '19:30', 'Wander', 'EBC-223', 'CIRC i MÚSICA', 'KONVENT'],
  [D(16), '21:30', 'Queerass(é)', 'Mau Cugat', 'PERFORMANCE', 'KONVENT'],
  [D(16), '22:30', 'Modern Nature - COCONAUTA', null, 'MÚSICA', 'KONVENT'],
  [D(17), '16:00', 'Espais Altres per a un Circ Altre', null, 'XERRADA', 'KONVENT'],
  [D(17), '18:00', 'Eclipse', 'Léo Rousselet', 'CIRC', 'Cal Rosal'],
  [D(17), '19:30', 'Décrochez-moi ça', 'Bêtes de Foire', 'CIRC', 'Cal Rosal'],
  [D(17), '22:00', 'Chou chou Ténèbres', 'Société protectrice de petites idées', 'CIRC', 'KONVENT'],
  [D(17), '23:30', 'Muovipussi + Schlaasss', null, 'MÚSICA', 'KONVENT'],
  [D(18), '15:30', 'Ròdols i Cigrons', 'Escarlata', 'CIRC', 'KONVENT'],
  [D(18), '17:00', 'Adeus', 'Oltrenotte', 'CIRC', 'Cal Rosal'],
  [D(18), '18:00', 'Ròdols i Cigrons', 'Escarlata', 'CIRC', 'KONVENT'],
  [D(18), '19:00', 'Décrochez-moi ça', 'Bêtes de Foire', 'CIRC', 'Cal Rosal'],
  [D(18), '22:00', 'Perdón', 'Los Informalls', 'DANSA', 'KONVENT'],
  [D(18), '23:30', 'Perera Elsewhere + Rafush', null, 'DJ', 'KONVENT'],
  [D(19), '13:30', 'Esperit!', null, 'MÚSICA', 'KONVENT'],
  [D(19), '14:00', 'The Sinner', 'Madame Paulette', 'TITELLES', 'KONVENT'],
  [D(19), '14:30', 'Dinar Popular', null, 'DINAR', 'KONVENT'],
  [D(19), '16:00', 'Rubbish Rabbit', 'Tony Clifton Circus', 'TEATRE de CARRER', 'Cal Rosal'],
  [D(19), '18:00', 'Ara o Mai', 'Cridacompany Jur', 'CIRC', 'KONVENT'],
  [D(19), '20:00', 'Kabaret Kontrast', null, 'CIRC i MÚSICA', 'Cal Rosal'],
];

// Una tarea se vincula a una compañía solo si su nombre cita a la obra, a la compañía o
// a una abreviatura clara (BTF). Se comparan textos sin tildes ni mayúsculas.
// Lo genérico ("Conciertos", "Montaje gradas"…) queda sin compañía.
export const REGLAS_TAREAS = [
  [/crulab|cru lab/, 'Cru Lab (Creació Express)'],
  [/bleu/, 'Cirque Pardí!'],
  [/\bbtf\b|betes de foire/, 'Bêtes de Foire'],
  [/copyleft/, 'Cie. NDE Nicanor de Elia'],
  [/kamchatka/, 'Kamchàtka'],
  [/rose bif/, 'Sarah Anglada'],
  [/miror/, 'Muchmuche Company'],
  [/claudio|walid|walk in progress/, 'Claudio Stellato + Pablo Molina'],
  [/wander/, 'EBC-223'],
  [/coconauta/, 'Modern Nature - COCONAUTA'],
  [/schlasss|muovipussi/, 'Muovipussi + Schlaasss'],
  [/compost|erreur/, 'Compost Collaps + ERREURJEAN'],
  [/chou chou/, 'Société protectrice de petites idées'],
  [/queerass/, 'Mau Cugat'],
  [/eclipse/, 'Léo Rousselet'],
  [/adeus/, 'Oltrenotte'],
  [/\bjur\b/, 'Cridacompany Jur'],
  [/escarlata/, 'Escarlata'],
  [/informals/, 'Los Informalls'],
  [/dolores/, 'My!Laika'],
  [/esperit/, 'Esperit!'],
  [/tony clif/, 'Tony Clifton Circus'],
  [/sinner/, 'Madame Paulette'],
  [/konvent klub/, 'Konvent Klub'],
  [/cabaret/, 'Kabaret Kontrast'],
  [/inutile/, 'Inutile Randonnée'],
];
